\c perma_stopwatch;

DROP TABLE IF EXISTS timer_pause;
DROP TABLE IF EXISTS timers;

CREATE TABLE timers (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    "startTime" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "paused" BOOLEAN DEFAULT FALSE,
    "totalPause" BIGINT DEFAULT 0,
    "currentPause" TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE timer_pause (
    id SERIAL PRIMARY KEY,
    "tsId" INTEGER REFERENCES timers(id) ON DELETE CASCADE,
    "pauseStart" TIMESTAMPTZ NOT NULL,
    "pauseEnd" TIMESTAMPTZ DEFAULT NULL
);